apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemma-server
  labels:
    app: gemma-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemma-server
  template:
    metadata:
      labels:
        app: gemma-server
    spec:
      containers:
      - name: gemma-server
        image: localhost:5000/gemma-server:latest  # ローカルのDockerイメージを指定
        ports:
        - containerPort: 8000
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: HF_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: gemma-server
spec:
  selector:
    app: gemma-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000  # NodePort用に指定するポート番号
  type: NodePort
