apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest  # Apacheの公式Dockerイメージ
          ports:
            - containerPort: 80  # Apacheがリッスンするポート
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Apacheのポート
  type: LoadBalancer  # 外部アクセスが必要な場合は LoadBalancer
